origin: TestHvSockDialNoTimeout: remove uses of t.Context()
It requires go1.24, but the module is currently go1.23;

  Error: hvsock_test.go:507:11: stdversion: testing.Context requires go1.24 or later (file is go1.23) (govet)
  	ctx := t.Context()
  	         ^

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>